### ISSUE TITLE
make Pos a record

### ISSUE THREAD

**Issue by itcowed** [MarcWeber/hasktags#18]
i have implemented the module field used by vim et. al, and in doing so i found it was probably best to ad a field to either `FoundThing` or `Pos`

motivated by this experience, i propose that `Pos` has too many fields and is frequently used in a nested getting sort of way that plays well with having field accessors. i would even argue that `FoundThing` should be recorded, but this is another story

i would be glad to submit prs if they are desired, but i thought i would open this issue before gallivanting off on an unwanted refactoring expedition

**Comment by jhenahan** [comment]
Implemented in 4a6c292.
