### ISSUE TITLE
cabal install on mac os failed.

### ISSUE THREAD

**Issue by godsme** [MarcWeber/hasktags#29]
Building hasktags-0.69.1...
Preprocessing library hasktags-0.69.1...
[1 of 3] Compiling DebugShow        ( src/DebugShow.hs, dist/build/DebugShow.o )

src/DebugShow.hs:17:1: warning: [-Wredundant-constraints]
    • Redundant constraint: Show a
    • In the type signature for:
           trace_ :: Show a => String -> a -> b -> b
[2 of 3] Compiling Tags             ( src/Tags.hs, dist/build/Tags.o )

src/Tags.hs:19:1: warning: [-Wtabs]
    Tab character found here, and in 38 further locations.
    Please use spaces instead.
[3 of 3] Compiling Hasktags         ( src/Hasktags.hs, dist/build/Hasktags.o )

src/Hasktags.hs:495:5: error:
    Ambiguous occurrence ‘isSymbolicLink’
    It could refer to either ‘System.Directory.isSymbolicLink’,
                             imported from ‘System.Directory’ at src/Hasktags.hs:31:1-23
                          or ‘System.Posix.Files.isSymbolicLink’,
                             imported from ‘System.Posix.Files’ at src/Hasktags.hs:38:1-25
                             (and originally defined in ‘unix-2.7.2.0:System.Posix.Files.Common’)
cabal: Leaving directory '/var/folders/5r/8w3bty650zxfc_48jt09kxz40000gn/T/cabal-tmp-91576/hasktags-0.69.1'

**Comment by bugthunk** [comment]
+1

**Comment by jhenahan** [comment]
Will be fixed in the next release by #30.
