### ISSUE TITLE
Please don't install an executable called "test"

### ISSUE THREAD

**Issue by peti** [MarcWeber/hasktags#32]
If in doubt, the name "hasktags-test" would probably be more appropriate. See https://github.com/NixOS/nixpkgs/pull/18403 for more details.

**Comment by chris-martin** [comment]
Was this fixed by 7fbce50?

**Comment by jhenahan** [comment]
Sorry, this was fixed by #31. I'll get that version onto Hackage shortly.

**Comment by jhenahan** [comment]
Released 0.69.2.1 and deprecated 0.69.2.
