### ISSUE TITLE
Emacs / Spacemacs reports an error of 'is not a valid tags table'

### ISSUE THREAD

**Issue by chrissound** [MarcWeber/hasktags#34]
Contents of `tags` file:

```
Main	./src/Main.hs	2
Main	./src/Main2.hs	2
comparePackage	./src/Main.hs	19
main	./Setup.hs	2
main	./src/Main.hs	27
main	./src/Main2.hs	19
```

**Comment by jhenahan** [comment]
Would you be able to post a minimal source file which generates an erroneous `tags` file? I also use Spacemacs, so I'll give this a look as soon as I can.

**Comment by chrissound** [comment]
This was due to using the '--ctags' instead of '--etags'. Thank you.
